# 10,000 ether is placed in the NaiveReceiverEchidna contract.
balanceContract: 10000000000000000000000
# Allow for multi-abi use
# What is this for lol?
multi-abi: true
testMode: "assertion"
corpusDir: corpus
testLimit: 50000